=== Alnaimi-/CYK-Parser-XSLT/grammar.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:complexType name="motherType">
    <xs:sequence>
      <xs:element minOccurs="2" maxOccurs="2" name="daughter" type="daughterType"/>
    </xs:sequence>
    <xs:attribute name="cat" type="categoryType" use="required"/>
  </xs:complexType>
  <xs:complexType name="daughterType">
    <xs:attribute name="cat" type="categoryType" use="required"/>
  </xs:complexType>
  <xs:complexType name="wordType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="cat" type="categoryType" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:element name="mother" type="motherType"/>
  <xs:element name="word" type="wordType"/>
  <xs:element name="grammar">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="rules">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" ref="mother"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="lexicalRules">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="word" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="startCat" type="categoryType" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="categoryType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="s"/>
      <xs:enumeration value="np"/>
      <xs:enumeration value="vp"/>
      <xs:enumeration value="cn"/>
      <xs:enumeration value="vt"/>
      <xs:enumeration value="dt"/>
      <xs:enumeration value="jj"/>
      <xs:enumeration value="wp"/>
      <xs:enumeration value="rp"/>
      <xs:enumeration value="pp"/>
      <xs:enumeration value="pr"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== Alnaimi-/CYK-Parser-XSLT/englishGrammar.xml
<?xml version="1.0" encoding="UTF-8"?>
<grammar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="grammar.xsd" startCat="s">
    <rules>
        <mother cat="s">
            <daughter cat="np"/>
            <daughter cat="vp"/>
        </mother>
        <mother cat="vp">
            <daughter cat="vt"/>
            <daughter cat="np"/>
        </mother>
        <mother cat="np">
            <daughter cat="dt"/>
            <daughter cat="cn"/>
        </mother>
        <mother cat="np">
            <daughter cat="np"/>
            <daughter cat="pp"/>
        </mother>
        <mother cat="np">
            <daughter cat="np"/>
            <daughter cat="wp"/>
        </mother>
        <mother cat="cn">
            <daughter cat="cn"/>
            <daughter cat="wp"/>
        </mother>
        <mother cat="pp">
            <daughter cat="pr"/>
            <daughter cat="np"/>
        </mother>
        <mother cat="wp">
            <daughter cat="rp"/>
            <daughter cat="vp"/>
        </mother>
        <mother cat="cn">
            <daughter cat="jj"/>
            <daughter cat="cn"/>
        </mother>
        <mother cat="np">
            <daughter cat="jj"/>
            <daughter cat="np"/>
        </mother>
    </rules>
    <lexicalRules>
        <word cat="vp">snores</word>
        <word cat="vt">likes</word>
        <word cat="np">john</word>
        <word cat="np">mary</word>
        <word cat="np">tuna</word>
        <word cat="cn">boy</word>
        <word cat="cn">girl</word>
        <word cat="cn">cat</word>
        <word cat="cn">tuna</word>
        <word cat="dt">the</word>
        <word cat="dt">a</word>
        <word cat="dt">any</word>
        <word cat="dt">every</word>
        <word cat="jj">tasty</word>
        <word cat="jj">greedy</word>
        <word cat="rp">who</word>
        <word cat="pr">with</word>
    </lexicalRules>
</grammar>
