=== Alnaimi-/CYK-Parser-XSLT/tree.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.0" vc:maxVersion="1.1">
    
    <!-- 
        Here we chose to put each tree (sentence) 
        into a TreeBank to enhance readability 
    -->
    <xs:element name="TreeBank">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="tree"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="tree">
        <xs:complexType>
        <xs:sequence>
            <xs:element maxOccurs="unbounded" ref="node"/>
        </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="node">
        <xs:complexType>                        
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="node"/>
                <xs:element ref="word"/>
            </xs:choice>
            
            <xs:attribute name="cat" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="word">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">                    
                    <xs:attribute name="cat" type="xs:string"/>    
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Alnaimi-/CYK-Parser-XSLT/tree.xml
<?xml version="1.0" encoding="UTF-8"?><TreeBank xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tree.xsd"><tree><node cat="s"><word cat="np">john</word><word cat="vp">snores</word></node></tree><tree><node cat="s"><word cat="np">mary</word><node cat="vp"><word cat="vt">likes</word><word cat="np">tuna</word></node></node></tree><tree><node cat="s"><word cat="np">mary</word><node cat="vp"><word cat="vt">likes</word><word cat="np">john</word></node></node></tree><tree><node cat="s"><word cat="np">john</word><node cat="vp"><word cat="vt">likes</word><node cat="np"><word cat="dt">the</word><word cat="cn">girl</word></node></node></node></tree><tree><node cat="s"><node cat="np"><word cat="dt">the</word><word cat="cn">cat</word></node><node cat="vp"><word cat="vt">likes</word><word cat="np">tuna</word></node></node></tree><tree><node cat="s"><node cat="np"><word cat="dt">the</word><word cat="cn">girl</word></node><node cat="vp"><word cat="vt">likes</word><node cat="np"><word cat="dt">the</word><word cat="cn">cat</word></node></node></node></tree><tree><node cat="s"><node cat="np"><node cat="np"><word cat="dt">a</word><word cat="cn">cat</word></node><node cat="pp"><word cat="pr">with</word><word cat="np">tuna</word></node></node><word cat="vp">snores</word></node></tree><tree><node cat="s"><node cat="np"><word cat="dt">the</word><word cat="cn">cat</word></node><node cat="vp"><word cat="vt">likes</word><node cat="np"><node cat="np"><word cat="dt">the</word><word cat="cn">girl</word></node><node cat="pp"><word cat="pr">with</word><node cat="np"><word cat="dt">the</word><word cat="cn">tuna</word></node></node></node></node></node></tree><tree><node cat="s"><node cat="np"><node cat="np"><word cat="dt">the</word><word cat="cn">boy</word></node><node cat="pp"><word cat="pr">with</word><node cat="np"><word cat="dt">a</word><node cat="cn"><word cat="jj">greedy</word><word cat="cn">cat</word></node></node></node></node><node cat="vp"><word cat="vt">likes</word><node cat="np"><node cat="np"><word cat="dt">every</word><word cat="cn">girl</word></node><node cat="pp"><word cat="pr">with</word><node cat="np"><word cat="jj">tasty</word><word cat="np">tuna</word></node></node></node></node></node></tree><tree><node cat="s"><node cat="np"><word cat="dt">the</word><node cat="cn"><word cat="cn">cat</word><node cat="wp"><word cat="rp">who</word><node cat="vp"><word cat="vt">likes</word><word cat="np">tuna</word></node></node></node></node><node cat="vp"><word cat="vt">likes</word><node cat="np"><word cat="dt">the</word><node cat="cn"><word cat="cn">boy</word><node cat="wp"><word cat="rp">who</word><word cat="vp">snores</word></node></node></node></node></node></tree></TreeBank>
